# Generated by Django 3.0 on 2023-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
              INSERT INTO main.profiles_profile
              SELECT * FROM main.oc_lettings_site_profile;
          """)
    ]
