# Generated by Django 3.0 on 2023-02-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
