# Generated by Django 3.0 on 2023-03-04 09:56

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('home_site', '0002_auto_20230227_1830'),
    ]

    operations = [
        migrations.RunSQL("""
                DROP TABLE oc_lettings_site_address;
                DROP TABLE oc_lettings_site_letting;
                DROP TABLE oc_lettings_site_profile;
            """)
    ]
